<a href="https://colab.research.google.com/github/waseemahmad1/es150lab5/blob/main/Ahmad_Waseem_ENGSCI_150_Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ES150: Introduction to Probability with Engineering Applications**

Lab #5: Markov Chains and Applications

Spring 2024

In this lab, we will use simulations to verify the theoretical characterizations of the steady-state distributions of Markov chains. We will also explore an application to Markov chains in natural lanaguge modelling.

**Part I: Steady-State Distributions of Markov chains**

Consider a 3-state Markov chain, whose transition matrix is given by

\begin{align}
P = \begin{bmatrix}0.2 & 0.4 & 0.4\\
0.45 & 0.45 & 0.1\\
0.3 & 0.3  & 0.4 \end{bmatrix}.
\end{align}

In the lectures, we have seen the following characterization of the long-term "steady-state" behaviors of this Markov chain:

\begin{align}\tag{1}
\lim_{n \to \infty} P^n = \begin{bmatrix}\pi_1 & \pi_2 & \pi_3\\
\pi_1 & \pi_2 & \pi_3\\
\pi_1 & \pi_2  & \pi_3 \end{bmatrix}.
\end{align}

In the above formula, $\pi_1, \pi_2, \pi_3$ are three numbers that can be determined by the following conditions:

1.   Normalization:
\begin{align}
\pi_1 + \pi_2 + \pi_3 = 1.
\end{align}
2.   Balance equation:
\begin{align}
\begin{bmatrix}\pi_1 & \pi_2 & \pi_3\end{bmatrix} = \begin{bmatrix}\pi_1 & \pi_2 & \pi_3\end{bmatrix} P.
\end{align}

***Step 1: Create a numpy array for P***

In [ ]:
import numpy as np

# type your code here: you can use np.array

P = np.array([
    [0.2, 0.4, 0.4],
    [0.45, 0.45, 0.1],
    [0.3, 0.3, 0.4]])

print(P)

[[0.2  0.4  0.4 ]
 [0.45 0.45 0.1 ]
 [0.3  0.3  0.4 ]]


***Step 2: Take several different integer powers of P***

Compute $P^2, P^5, P^{10}$ and $P^{100}$. Print these matrices, and verify that, as $n$ increases, $P^n$ indeed converges to the form $\begin{bmatrix}\pi_1 & \pi_2 & \pi_3\\
\pi_1 & \pi_2 & \pi_3\\
\pi_1 & \pi_2  & \pi_3 \end{bmatrix}$.

Moreover, verify that $\pi_1, \pi_2, \pi_3$ that you get from $P^{100}$ indeed satisfy the normalization and balence equations.



In [ ]:
# Type your code here
# Hint: To compute matrix power, you should use np.linalg.matrix_power(P, n), where n is the power

P = np.array([
    [0.2, 0.4, 0.4],
    [0.45, 0.45, 0.1],
    [0.3, 0.3, 0.4]])

second_power = np.linalg.matrix_power(P, 2)
fifth_power = np.linalg.matrix_power(P, 5)
tenth_power = np.linalg.matrix_power(P, 10)
one_hundreth_power = np.linalg.matrix_power(P, 100)
one_thousandth_power = np.linalg.matrix_power(P, 1000)

print(second_power, "\n")
print(fifth_power, "\n")
print(tenth_power, "\n")
print(one_hundreth_power, "\n")
print(one_thousandth_power, "\n")

row_sums_one_hundreth = np.sum(one_hundreth_power, axis=1)
product = np.dot(P, one_hundreth_power)

print("Normalization (pi_1 + pi_2 + pi_3): ", row_sums_one_hundreth)

print("Balance Equation:\n", product, "\n")


print("Hence, we have indeed satisfied the normalization and balance equations")

[[0.34   0.38   0.28  ]
 [0.3225 0.4125 0.265 ]
 [0.315  0.375  0.31  ]] 

[[0.3260075  0.3912775  0.282715  ]
 [0.32619656 0.39142781 0.28237563]
 [0.32602688 0.39116438 0.28280875]] 

[[0.32608695 0.39130433 0.28260871]
 [0.32608698 0.39130439 0.28260863]
 [0.32608693 0.3913043  0.28260876]] 

[[0.32608696 0.39130435 0.2826087 ]
 [0.32608696 0.39130435 0.2826087 ]
 [0.32608696 0.39130435 0.2826087 ]] 

[[0.32608696 0.39130435 0.2826087 ]
 [0.32608696 0.39130435 0.2826087 ]
 [0.32608696 0.39130435 0.2826087 ]] 

Normalization (pi_1 + pi_2 + pi_3):  [1. 1. 1.]
Balance Equation:
 [[0.32608696 0.39130435 0.2826087 ]
 [0.32608696 0.39130435 0.2826087 ]
 [0.32608696 0.39130435 0.2826087 ]] 

Hence, we have indeed satisfied the normalization and balance equations


***Step 3: The long-term frequency of visiting a given state***

In the lectures, we provide one interpretation of the probabilities $\pi_1, \pi_3, \pi_3$. Suppose we simulate the Markov chain for $n$ steps. Let $V_1(n)$ denote the number of times the state 1 has been visited. Similarly, we can define $V_2(n)$ and $V_3(n)$ to count the number of times states 2 and 3 have been visited within $n$ steps of the Markov chain transition. Then we know that
\begin{align}
  \lim_{n \to \infty} \frac{V_1(n)}{n} = \pi_1, \qquad  \lim_{n \to \infty} \frac{V_2(n)}{n} = \pi_2, \qquad  \lim_{n \to \infty} \frac{V_3(n)}{n} = \pi_3.
\end{align}

In this step, we will verify the above characterization by simulating the Markov chain for $n = 10^5$ steps.

In [ ]:
# Type your code here

n = 10**5 # length of simulations

visits = np.zeros(3) # an array recording the number of times each of the three states have been visited

curr_state = 0 # suppose we start the Markov chain at state 1. Note that we encode state 1 by index 0, due to NumPy's 0-based indexing scheme.

# continue your code here. To simulate the evolution of Markov chains, you can use np.random.choice

for _ in range(n):
    curr_state = np.random.choice([0, 1, 2], p=P[curr_state])
    visits[curr_state] += 1

probability = visits / n

print("Empirical probabilities:", probability, "\n")
print(one_hundreth_power, "\n")

print("We can see that our probabilities are close to pi_1, pi_2, and pi_3. If n was even larger, we should see these probabilities become very very very close/equivalent")

Empirical probabilities: [0.32481 0.39056 0.28463] 

[[0.32608696 0.39130435 0.2826087 ]
 [0.32608696 0.39130435 0.2826087 ]
 [0.32608696 0.39130435 0.2826087 ]] 

We can see that our probabilities are close to pi_1, pi_2, and pi_3. If n was even larger, we should see these probabilities become very very very close/equivalent


**Part II: Application of Markov Chains: Modelling and generating English sentences**

In this part, we will delve into a significant application of Markov chains—the modeling of natural languages. Our approach involves using a text file, such as a classical novel, as the input. Each unique word and punctuation mark within the text is mapped to a unique state (in a process known as tokenization).

For the purposes of our model, suppose the text contains 3000 unique words and punctuation marks. This setup leads us to construct a Markov chain consisting of 3000 states. The transitions between these states are determined by a $3000 \times 3000$ transition matrix $P$. We will learn this matrix directly from the input text to accurately reflect the linguistic structure of the source material.

Once the Markov chain is established and the transition matrix is learned, we can use this model to generate new sentences. These sentences are expected to resemble coherent English language constructs, mirroring the style and vocabulary of the input text.

**Step 1: Read the input text and map words/punctuation marks into unique tokens**

In [ ]:
# The following are some utilitie functions

def read_file(filename):
    with open(filename, 'r', encoding='utf-8') as file:
        text = file.read()
    return text

import re, nltk

def preprocess(text):
    # Ensure space around punctuation
    text = re.sub(r'([.,;:!?\(\)])', r' \1 ', text)
    # Replace multiple spaces with a single space
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download('punkt')  # Download the necessary datasets

def tokenize(text):
    words = nltk.word_tokenize(text)
    return words

def map_words_to_tokens(words):
    word_to_index = {}
    index_to_word = {}
    for word in words:
        if word not in word_to_index:
            index = len(word_to_index)
            word_to_index[word] = index
            index_to_word[index] = word
    return word_to_index, index_to_word

from urllib.request import urlopen

def read_text_from_url_builtin(url):
    with urlopen(url) as response:
        text = response.read().decode('utf-8')
    return text

import textwrap


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
# Let's specify the source material. Here I use Alice's Adventures in Wonderland. You should experiment with different sources
url1 = 'https://www.gutenberg.org/cache/epub/11/pg11.txt'

text1 = read_text_from_url_builtin(url)
text1 = preprocess(text)

words1 = tokenize(text) # words is an array containing consecutive words in the text. You can print it to examine its content.

# These two mappings allow us to map unique words to integers (i.e. state of a Markov chain) and vice versa.
word_to_index, index_to_word = map_words_to_tokens(words1)

In [ ]:
# Type your code here

# 1. Print words, to examine its context

print(words1)

# 2. Print index_to_word[10], index_to_word[100], word_to_index['This'] ... in order to understand what these two dictionaries are really doing.

print(index_to_word[10])
print(index_to_word[100])
print(word_to_index['This'])

# 3. To test your understanding, what is the index associated with the word "mouse"?

print("The index associated with the word 'mouse' is:", word_to_index['mouse'])

In [ ]:
gatsby_url2 = 'https://www.gutenberg.org/cache/epub/64317/pg64317.txt'

text2 = read_text_from_url_builtin(gatsby_url2)
text2 = preprocess(text2)
words2 = tokenize(text2)
word_to_index, index_to_word = map_words_to_tokens(words2)

print(words2)
print(index_to_word[1000])
print(index_to_word[1500])
print(word_to_index['This'])
print("The index associated with the word 'Daisy' is:", word_to_index['Daisy'])

**Step 2: Learn the transition matrix of the Markov chain**

In [ ]:
# Type your code here

M = len(word_to_index) # M is the number of states in the Markov chain
P = np.zeros((M, M))

# Learn the transition matrix P from the input text
# Don't forget to normalize P so that it's a valid transition matrix

transition_counts = np.zeros((M, M))

for i in range(len(words1) - 1):
    current_word_index = word_to_index[words1[i]]
    next_word_index = word_to_index[words1[i+1]]
    transition_counts[current_word_index, next_word_index] += 1

# Normalize
P = transition_counts / transition_counts.sum(axis=1, keepdims=True)

print(P)

[[0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.33333333 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


**Step 3: Generate new sentences from the learned Markov chain**

In [ ]:
# Type your code here

nsamples = 5 # how many different sentences we want to generate
sentence_len = 100 # length of each sentence

sentences = []

for _ in range(nsamples):
    current_state = np.random.choice(M)
    sentence = [index_to_word[current_state]]

    for _ in range(sentence_len - 1):
        current_state = np.random.choice(M, p=P[current_state])
        sentence.append(index_to_word[current_state])

    sentence_str = ' '.join(sentence)
    sentences.append(sentence_str)


for i, sentence in enumerate(sentences):
    print(f"{sentence}\n")

corrupt data , and then at all else . “ Now , as follows : — “ You may be listening , ” he spoke at once or 1 . “ Off with the sea— ” “ until there seemed to it . “ Sure , and Northumbria , ” ( trademark/copyright ) “ she went off , who was walking hand upon Bill , ” the trees under its head unless you if you for fear lest she had happened , going out with its waistcoat-pocket_ , “ I give all the terms of sitting by U . “

shake at everything that it , “ Can you were never forgotten that , ” the Tarts ? ” “ I can do such a little of her idea what porpoise , but I wonder what it , ” said : she went on their own business , they used up at first question the Queen ’ s done , and then a wonderful Adventures in a moment : “ What ! wow ! ” said the method you in her . ” “ Go on tiptoe , “ Suppose we can _ever_ finish , “ How fond of eating

custard , swallowing down , ” but then—I shouldn ’ ll stay down at the Dormouse crossed the dance . “ if I want to abide by two guinea-pigs , and address

**(Optional) Step 4: Invitation to improve the code and the modeling**

As we continue to refine our code and model for generating text, I want to outline some potential improvements that could significantly increase the quality of the sentences we produce. By implementing these strategies, we can better mimic the natural flow of English language. This (optional) part is meant as an open-ended invitation to all of you to experiment with new ideas. I look forward to seeing how far we can push the boundaries.

1. Second-Order Markov Chain: This approach involves extending our current model to consider the two most recent words (a "context window" of two) instead of just the last one. By accounting for both the current and the previous word, this method could more accurately capture the complex statistical correlations typically found in English sentence structures.

2. Start and End Symbols: Another enhancement could involve integrating special symbols that specifically denote the start and end of sentences. This adjustment would help in generating more coherent and contextually appropriate sentences, providing clear cues about sentence boundaries which are essential for realistic text generation.

3. Consider using more advanced models such as recurrent neural networks (RNNs), especially LSTM (Long Short-Term Memory) or GRU (Gated Recurrent Units), which are capable of remembering longer sequences of data and can generate more contextually relevant sentences.


In [ ]:
# Type your code here
